import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import promptsRouter from "./prompts";
import contentRouter from "./content";
import thumbnailsRouter from "./thumbnails";
import videoModelRouter from "./video-model";
import pdfsRouter from "./pdfs";
import apiKeysRouter from "./api-keys";
import paymentGatewaysRouter from "./payment-gateways";
import featuresRouter from "./features";
import settingsRouter from "./settings";
import chatRouter from "./chat";
import dashboardRouter from "./dashboard";
import seedRouter from "./seed";
import landingPageRouter from "./landing-page";
import scriptsRouter from "./scripts";
import usageRouter from "./usage";
import productsRouter from "./products";
import walletRouter from "./wallet";
import trendingRouter from "./trending";
import subscriptionsRouter from "./subscriptions";
import pagesRouter from "./pages";
import affiliateRouter from "./affiliate";
import broadcastRouter from "./broadcast";
import adminAffiliatesRouter from "./admin-affiliates";
import automationsRouter from "./automations";
import adminAutomationsRouter from "./admin-automations";
import adminProductsRouter from "./admin-products";
import checkoutRouter from "./checkout";
import emailMarketingRouter from "./email-marketing";
import revenueRouter from "./revenue";
import voiceRouter from "./voice";
import videoGeneratorRouter from "./video-generator";
import cronRouter from "./cron";
import scryvoxRouter from "./scryvox";
import scryvoxProductRouter from "./scryvox-product";
import scryvoxKnowledgeRouter from "./scryvox-knowledge";
import templatesRouter from "./templates";
import marketplaceRouter from "./marketplace";
import adminTemplatesRouter from "./admin-templates";
import affiliateProgramsRouter from "./affiliate-programs";
import aiAgentsRouter from "./ai-agents";
import customOffersRouter from "./custom-offers";
import { promptPackagesRouter } from "./prompt-packages";
import workspaceRouter from "./workspace";
import adminWorkspaceRouter from "./admin-workspace";
import saasBuilderRouter from "./saas-builder";
import videoAgentRouter from "./video-agent";
import uploadsRouter from "./uploads";
import r2AdminRouter from "./r2-admin";
import creditsRouter from "./credits";
import toolFlagsRouter from "./tool-flags";
import coursesRouter from "./courses";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(promptsRouter);
router.use(contentRouter);
router.use(thumbnailsRouter);
router.use(videoModelRouter);
router.use(pdfsRouter);
router.use(apiKeysRouter);
router.use(paymentGatewaysRouter);
router.use(featuresRouter);
router.use(settingsRouter);
router.use(chatRouter);
router.use(dashboardRouter);
router.use(seedRouter);
router.use(landingPageRouter);
router.use(scriptsRouter);
router.use(usageRouter);
router.use(productsRouter);
router.use(walletRouter);
router.use(trendingRouter);
router.use(subscriptionsRouter);
router.use(pagesRouter);
router.use(affiliateRouter);
router.use(broadcastRouter);
router.use(adminAffiliatesRouter);
router.use(automationsRouter);
router.use(adminAutomationsRouter);
router.use(adminProductsRouter);
router.use(checkoutRouter);
router.use(emailMarketingRouter);
router.use(revenueRouter);
router.use(voiceRouter);
router.use(videoGeneratorRouter);
router.use(cronRouter);
router.use(scryvoxRouter);
router.use(scryvoxProductRouter);
router.use(scryvoxKnowledgeRouter);
router.use(templatesRouter);
router.use(marketplaceRouter);
router.use(adminTemplatesRouter);
router.use(affiliateProgramsRouter);
router.use(aiAgentsRouter);
router.use(customOffersRouter);
router.use(promptPackagesRouter);
router.use(workspaceRouter);
router.use(adminWorkspaceRouter);
router.use(saasBuilderRouter);
router.use(videoAgentRouter);
router.use(uploadsRouter);
router.use(r2AdminRouter);
router.use(creditsRouter);
router.use(toolFlagsRouter);
router.use(coursesRouter);

export default router;
