import { Router } from "express";
import { db } from "@workspace/db";
import { pagesTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { requireAdmin } from "./auth";

const router = Router();

const DEFAULT_PAGES = [
  {
    slug: "about",
    title: "About Us",
    content: `# About ViralCraft Studio

ViralCraft Studio is the all-in-one AI platform for creators, entrepreneurs, and marketers who want to build digital products and grow their online presence — fast.

## Our Mission

We believe anyone with an idea deserves a system to turn that idea into income. That's why we built ViralCraft Studio: to remove the complexity from digital product creation, marketing, and selling.

## What We Do

We help you:
- Create sellable digital products (PDF guides, ebooks) using AI
- Generate high-converting landing pages automatically  
- Publish products to your own online store
- Create viral marketing content for TikTok, YouTube, Twitter, and more
- Track your sales and grow your income

## Who We Serve

ViralCraft Studio is built for:
- Content creators who want to monetize their knowledge
- Entrepreneurs building digital product businesses
- Marketers who want AI-powered content at scale
- Anyone who wants to make money online without technical skills

## Contact Us

Have questions? Reach out to us at support@viralcraft.studio`,
    metaDescription: "Learn about ViralCraft Studio — the AI platform for digital product creation and monetization.",
  },
  {
    slug: "privacy-policy",
    title: "Privacy Policy",
    content: `# Privacy Policy

**Last updated: ${new Date().toLocaleDateString()}**

## Introduction

ViralCraft Studio ("we", "us", or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our platform.

## Information We Collect

**Account Information:** When you register, we collect your name, email address, and password (stored encrypted).

**Usage Data:** We collect information about how you use the platform, including content generated, pages visited, and features used.

**Payment Information:** Payment details are processed by our payment providers (Paystack, LemonSqueezy, Paddle). We do not store raw card numbers.

## How We Use Your Information

- To provide and improve our services
- To process payments and manage your account
- To send transactional emails (receipts, password resets)
- To analyze usage patterns and improve the platform

## Data Security

We use industry-standard encryption and security practices to protect your data. Your password is hashed and never stored in plain text.

## Your Rights

You have the right to:
- Access your personal data
- Request deletion of your account and data
- Export your data
- Opt out of marketing communications

## Contact

For privacy-related questions, contact: privacy@viralcraft.studio`,
    metaDescription: "ViralCraft Studio Privacy Policy — how we collect, use, and protect your data.",
  },
  {
    slug: "terms",
    title: "Terms of Service",
    content: `# Terms of Service

**Last updated: ${new Date().toLocaleDateString()}**

## Acceptance of Terms

By using ViralCraft Studio, you agree to these Terms of Service. If you do not agree, please do not use our platform.

## Use of the Platform

You may use ViralCraft Studio to:
- Create and sell digital products
- Generate AI-powered content
- Manage your online store

You may NOT use our platform to:
- Create illegal, harmful, or fraudulent content
- Infringe on intellectual property rights
- Spam or harass other users
- Circumvent our payment systems

## AI-Generated Content

Content generated by our AI tools is provided as-is. You are responsible for reviewing and ensuring the accuracy of all AI-generated content before publishing or selling it.

## Intellectual Property

You own the content you create using our platform. By using our AI generation features, you grant us a limited license to process your inputs to deliver the service.

## Payment & Subscriptions

- Free plan is available with limited features
- Pro plan is $29/month, billed monthly
- 2-day free trial available for new accounts
- Platform takes a 10% commission on product sales

## Limitation of Liability

ViralCraft Studio is not responsible for earnings or sales results. Results vary based on effort, market conditions, and individual factors.

## Contact

For legal inquiries: legal@viralcraft.studio`,
    metaDescription: "ViralCraft Studio Terms of Service — rules and guidelines for using our platform.",
  },
  {
    slug: "refund-policy",
    title: "Refund Policy",
    content: `# Refund Policy

**Last updated: ${new Date().toLocaleDateString()}**

## Subscription Refunds

**Free Trial:** We offer a 2-day free trial. No charge until the trial ends.

**Monthly Subscriptions:** We offer a 7-day refund window for monthly subscriptions if you are not satisfied. Contact support within 7 days of your charge.

**How to Request:** Email support@viralcraft.studio with your account email and reason for refund.

## Digital Product Purchases

When you purchase a digital product from a creator on our platform:

- All digital product sales are **final** by default (digital goods cannot be returned)
- If a product is materially different from its description, contact us within 7 days
- We will investigate and may issue a refund at our discretion
- Fraudulent listings are removed and buyers receive full refunds

## Creator Payouts

- Creator earnings are credited at 90% of the sale price
- Payouts are processed within 3-5 business days of withdrawal request
- Minimum withdrawal is $50
- Refunded orders are deducted from creator wallet balance

## Contact Us

To request a refund or dispute a charge:
- Email: support@viralcraft.studio
- Include your order ID or account email
- We respond within 24-48 business hours`,
    metaDescription: "ViralCraft Studio Refund Policy — our commitment to fair refunds for subscriptions and digital products.",
  },
];

async function ensureDefaultPages() {
  for (const page of DEFAULT_PAGES) {
    const existing = await db.select().from(pagesTable).where(eq(pagesTable.slug, page.slug)).limit(1);
    if (existing.length === 0) {
      await db.insert(pagesTable).values(page);
    }
  }
}

router.get("/pages/:slug", async (req, res) => {
  try {
    await ensureDefaultPages();
    const [page] = await db.select().from(pagesTable).where(eq(pagesTable.slug, req.params.slug)).limit(1);
    if (!page || !page.isPublished) {
      res.status(404).json({ error: "Page not found" });
      return;
    }
    res.json(page);
  } catch (err: any) {
    req.log?.error?.({ err }, "GetPage error");
    res.status(500).json({ error: "Server error" });
  }
});

router.get("/admin/pages", requireAdmin, async (req: any, res) => {
  try {
    await ensureDefaultPages();
    const pages = await db.select().from(pagesTable);
    res.json(pages);
  } catch (err) {
    req.log.error({ err }, "ListPages error");
    res.status(500).json({ error: "Server error" });
  }
});

router.patch("/admin/pages/:slug", requireAdmin, async (req: any, res) => {
  try {
    const { title, content, metaDescription, isPublished } = req.body;
    const existing = await db.select().from(pagesTable).where(eq(pagesTable.slug, req.params.slug)).limit(1);

    if (existing.length === 0) {
      const [created] = await db.insert(pagesTable).values({
        slug: req.params.slug,
        title: title ?? req.params.slug,
        content: content ?? "",
        metaDescription,
        isPublished: isPublished ?? true,
      }).returning();
      res.json(created);
    } else {
      const [updated] = await db.update(pagesTable)
        .set({
          ...(title !== undefined && { title }),
          ...(content !== undefined && { content }),
          ...(metaDescription !== undefined && { metaDescription }),
          ...(isPublished !== undefined && { isPublished }),
          updatedAt: new Date(),
        })
        .where(eq(pagesTable.slug, req.params.slug))
        .returning();
      res.json(updated);
    }
  } catch (err: any) {
    req.log.error({ err }, "UpdatePage error");
    res.status(500).json({ error: "Server error" });
  }
});

export default router;
