import { Router } from "express";
import { requireAuth } from "./auth";
import { ALL_TRENDING_IDEAS } from "../data/trending/index";

const router = Router();

const ALL_IDEAS = [
  // ── HEALTH HOME REMEDIES ──────────────────────────────────────────────────
  { title: "Apple Cider Vinegar Miracle Guide", description: "50+ proven home remedies using ACV for weight loss, digestion, skin & energy", whyTrending: "Millions searching daily for natural alternatives to expensive pills", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🍎" },
  { title: "Flat Belly Without the Gym", description: "Natural home remedies and drinks that shrink belly fat in 30 days", whyTrending: "Post-pandemic belly fat is the #1 health complaint worldwide", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "🫚" },
  { title: "The 7-Day Detox Tea Bible", description: "Homemade detox teas and herbal blends to cleanse liver, gut, and skin", whyTrending: "Detox teas going viral on TikTok with millions of views", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🍵" },
  { title: "Natural Blood Pressure Fix", description: "Herbal and dietary remedies that lower blood pressure without medication", whyTrending: "1 in 3 adults has high blood pressure and fears lifetime medication", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "❤️" },
  { title: "Sugar Detox in 14 Days", description: "Step-by-step plan to beat sugar addiction using natural substitutes", whyTrending: "Diabetes and prediabetes at all-time high, people desperate for solutions", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🚫" },
  { title: "Knee & Joint Pain Home Cures", description: "Natural anti-inflammatory remedies, oils and exercises for joint relief", whyTrending: "70M Americans suffer joint pain and want drug-free solutions", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "🦵" },
  { title: "Sleep Like a Baby Tonight", description: "Natural remedies, teas, and routines that cure insomnia without pills", whyTrending: "Sleep aids market exploding, people tired of melatonin side effects", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "😴" },
  { title: "Ginger Power: 100 Home Remedies", description: "Every healing use of ginger for nausea, pain, immunity, and weight loss", whyTrending: "Ginger content goes massively viral across health platforms", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🫚" },
  { title: "Reverse Diabetes Naturally", description: "Diet, lifestyle and natural remedies shown to lower blood sugar fast", whyTrending: "537M diabetics worldwide searching for natural management strategies", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Health & Home Remedies", emoji: "🩺" },
  { title: "Turmeric: The Golden Healer", description: "Anti-inflammatory turmeric remedies for arthritis, skin, weight, and immunity", whyTrending: "Turmeric supplements market hitting $1B+ — people want the DIY version", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "✨" },
  { title: "Hormone Balance for Women 35+", description: "Natural food, herb and lifestyle protocols to balance hormones after 35", whyTrending: "Perimenopause awareness exploding on social media — massive underserved market", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Health & Home Remedies", emoji: "🌸" },
  { title: "Home Remedies for Thyroid", description: "Dietary and lifestyle remedies to support thyroid function naturally", whyTrending: "Thyroid disorders affecting 200M+ worldwide, most undiagnosed", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "🦋" },
  { title: "Natural Skincare Recipes Book", description: "50 DIY face masks, serums and creams from kitchen ingredients", whyTrending: "Clean beauty trend driving massive demand for homemade skincare", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "✨" },
  { title: "Headache & Migraine Relief Guide", description: "Natural pressure points, oils and remedies to stop migraines in minutes", whyTrending: "1 billion migraine sufferers worldwide seeking drug-free help", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🧠" },
  { title: "Gut Healing Protocol", description: "Heal leaky gut, IBS and bloating with food and home remedies in 21 days", whyTrending: "Gut health is the #1 trending health topic with billions of views on TikTok", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Health & Home Remedies", emoji: "🌿" },

  // ── FITNESS & BODY TRANSFORMATION ─────────────────────────────────────────
  { title: "Bigger Hips & Rounder Booty Guide", description: "Science-backed exercises and nutrition to grow hips and glutes at home", whyTrending: "Hip/booty content gets billions of views, massive demand for structured guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "🍑" },
  { title: "Thicker Thighs in 30 Days", description: "Progressive home workout plan specifically for thigh growth without equipment", whyTrending: "Body positive movement driving demand for targeted muscle growth guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "💪" },
  { title: "Build Muscle at Home for Men", description: "Complete bodyweight and minimal equipment program for muscle gain without gym", whyTrending: "Home fitness market grew 400% and stayed there — gym memberships declining", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "🏋️" },
  { title: "Slim Waist Training Bible", description: "Waist cinching exercises, diet protocols and natural methods for hourglass shape", whyTrending: "Hourglass body is the most searched fitness goal on social media", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "⌛" },
  { title: "Flat Stomach in 28 Days", description: "Specific ab exercises, meal plan and bloating remedies for visible results", whyTrending: "Weight loss is always the #1 New Year resolution — demand never drops", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "🔥" },
  { title: "Lose 20lbs Without Starving", description: "Sustainable calorie deficit plan with real foods and no extreme dieting", whyTrending: "Yo-yo dieting epidemic — people desperate for something that actually works", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "⚡" },
  { title: "Over 40 Fat Loss Blueprint", description: "Metabolism-specific program for men and women to lose fat after 40", whyTrending: "Baby boomers and Gen X are the fastest-growing fitness market segment", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Fitness & Body", emoji: "💥" },
  { title: "Postpartum Body Comeback Guide", description: "Safe exercises and meal plan for new moms to regain their pre-baby body", whyTrending: "4M babies born per year in US — massive underserved postpartum fitness market", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Fitness & Body", emoji: "👶" },
  { title: "7-Minute Morning Stretch Routine", description: "Daily stretching for flexibility, posture, and pain-free living", whyTrending: "Desk workers flooding gyms with back pain — stretching content exploding", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Fitness & Body", emoji: "🧘" },
  { title: "Brazilian Booty Program", description: "8-week workout program inspired by Brazilian training methods for glute growth", whyTrending: "Brazilian fitness culture going viral globally, driving product demand", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "🌟" },

  // ── MAKE MONEY ONLINE ─────────────────────────────────────────────────────
  { title: "Zero to $5,000 Selling Digital Products", description: "Step-by-step guide to creating, launching and selling PDF guides online", whyTrending: "Digital product success stories going viral — massive aspirational demand", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "💰" },
  { title: "AI Side Hustle Blueprint 2025", description: "10 proven ways to make $3,000+/month using free AI tools from your phone", whyTrending: "AI tools accessible to everyone — people want actionable income guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🤖" },
  { title: "TikTok Shop Seller Playbook", description: "Complete guide to finding products, setting up shop and getting first 100 sales", whyTrending: "TikTok Shop generated $20B in 2024 — fastest growing e-commerce platform", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 37, category: "Make Money Online", emoji: "🛒" },
  { title: "Faceless YouTube Automation Guide", description: "Build a $10k/month YouTube channel without showing your face using AI", whyTrending: "Faceless channels with AI voiceovers dominating YouTube growth in 2025", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "📹" },
  { title: "Etsy Digital Downloads Goldmine", description: "How to open, optimize and scale an Etsy shop selling digital downloads", whyTrending: "Digital downloads on Etsy grew 180% — sellers making $10-50K/month", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🛍️" },
  { title: "Fiverr & Freelancing Launchpad", description: "How to land $100-500/day clients on Fiverr in 30 days with zero experience", whyTrending: "Remote work demand permanent — freelancing market at $1.5T globally", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "💼" },
  { title: "Amazon FBA Quick Start Guide", description: "Find profitable products and launch on Amazon with under $1,000 budget", whyTrending: "Amazon FBA still #1 fastest way to build passive income business", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "📦" },
  { title: "ChatGPT Freelancing Manual", description: "Use ChatGPT to offer writing, marketing and content services at premium rates", whyTrending: "Businesses spending $400B+ on freelance services — AI gives edge", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🤖" },
  { title: "Instagram Monetization Masterclass", description: "Turn 1,000 followers into consistent income through products and sponsorships", whyTrending: "Micro-influencer monetization now outperforms celebrity accounts in ROI", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "📸" },
  { title: "Print-on-Demand Empire Blueprint", description: "Design and sell custom products on Printful, Redbubble, Printify with no inventory", whyTrending: "POD market growing 26% annually — barriers to entry are zero", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🎨" },
  { title: "Canva Side Hustle Profits", description: "Make $2,000-5,000/month selling Canva templates on Etsy and social media", whyTrending: "Canva has 170M users — template demand growing faster than supply", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Make Money Online", emoji: "🖼️" },
  { title: "Passive Income Streams Bible", description: "15 proven passive income models that require minimal ongoing work", whyTrending: "Post-pandemic financial insecurity driving massive interest in passive income", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "💸" },
  { title: "Dropshipping in 2025: New Model", description: "Updated dropshipping strategies that actually work in today's competitive market", whyTrending: "Old dropshipping guides are outdated — need for 2025-specific strategies", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "🚀" },
  { title: "High-Ticket Closing Mastery", description: "How to close $2,000-$10,000 deals over the phone with no pressure tactics", whyTrending: "High-ticket sales is the fastest way to hit 6 figures and demand is massive", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Make Money Online", emoji: "🎯" },

  // ── PERSONAL FINANCE ──────────────────────────────────────────────────────
  { title: "Debt-Free in 12 Months Plan", description: "Proven strategy to eliminate all consumer debt in one year on any income", whyTrending: "US consumer debt hit $18T — desperation for structured debt payoff plans", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Personal Finance", emoji: "📊" },
  { title: "First-Time Homebuyer Cheatsheet", description: "Everything nobody tells first-time buyers about mortgages, agents, and offers", whyTrending: "Housing market confusion at all-time high — buyers need plain-English guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Personal Finance", emoji: "🏠" },
  { title: "Build $10K Emergency Fund Fast", description: "Step-by-step savings challenges and strategies to build emergency fund quickly", whyTrending: "65% of Americans can't cover $1,000 emergency — savings anxiety exploding", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Personal Finance", emoji: "🐷" },
  { title: "Crypto for Absolute Beginners", description: "Plain-English guide to buying, storing and profiting from cryptocurrency safely", whyTrending: "Bitcoin above $100K driving millions of new investors into crypto market", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Personal Finance", emoji: "₿" },
  { title: "Credit Score Repair Playbook", description: "Step-by-step system to raise your credit score by 100+ points in 90 days", whyTrending: "Bad credit costs average American $200K in lifetime interest — huge pain", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Personal Finance", emoji: "📈" },
  { title: "Stock Market Beginners Blueprint", description: "How to start investing with $100 and build wealth over time", whyTrending: "Stock market interest at all-time high among millennials and Gen Z", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Personal Finance", emoji: "📉" },
  { title: "Tax Saving Secrets for Side Hustlers", description: "Legal deductions and strategies side hustlers use to keep more money", whyTrending: "50M+ side hustlers overpaying taxes because they don't know the rules", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Personal Finance", emoji: "💵" },
  { title: "Frugal Living: $2K/Month Budget Guide", description: "How to live well on a tight budget and still save 20% of income", whyTrending: "Inflation making frugal living guides massively popular across all demographics", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Personal Finance", emoji: "🧾" },

  // ── MENTAL HEALTH & WELLNESS ──────────────────────────────────────────────
  { title: "30-Day Anxiety Reset Program", description: "Natural techniques, journaling and mindset shifts to overcome anxiety without medication", whyTrending: "Anxiety disorders are now the #1 mental health condition globally", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Mental Health & Wellness", emoji: "🧘" },
  { title: "Inner Child Healing Workbook", description: "Guided exercises to heal childhood wounds and break negative patterns", whyTrending: "Inner child healing viral on TikTok with 5B+ views — massive product demand", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Mental Health & Wellness", emoji: "💙" },
  { title: "Morning Routine for High Performance", description: "Proven 60-minute morning system used by top performers worldwide", whyTrending: "Productivity and morning routine content consistently ranks in top trending categories", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Mental Health & Wellness", emoji: "☀️" },
  { title: "Quit Overthinking Forever", description: "Practical CBT-based techniques to silence the inner critic and stop rumination", whyTrending: "Overthinking is the most searched mental health term after anxiety", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Mental Health & Wellness", emoji: "🧠" },
  { title: "Shadow Work Journal 2025", description: "40 guided shadow work prompts to unlock emotional freedom and self-understanding", whyTrending: "Shadow work content gets 2B+ views — digital journals outselling physical ones", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Mental Health & Wellness", emoji: "🌑" },
  { title: "Confidence Code for Women", description: "Science-backed confidence building system for women in career and relationships", whyTrending: "Women's empowerment content drives enormous sales on every digital platform", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Mental Health & Wellness", emoji: "👑" },
  { title: "Meditation for Busy People", description: "5-minute evidence-based meditation practices that work even for skeptics", whyTrending: "Headspace and Calm at 100M+ users — people want free alternatives", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Mental Health & Wellness", emoji: "🕯️" },

  // ── RELATIONSHIPS & DATING ────────────────────────────────────────────────
  { title: "Attract Your Ideal Partner Guide", description: "Psychology-based attraction strategies that work on dating apps and in real life", whyTrending: "Dating app fatigue creating demand for real-world attraction strategies", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Relationships", emoji: "❤️" },
  { title: "Save Your Marriage Playbook", description: "Communication frameworks and intimacy rebuilding strategies for couples in crisis", whyTrending: "Divorce rate climbing — couples actively searching for save-the-marriage content", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Relationships", emoji: "💑" },
  { title: "Texting Bible for Men", description: "What to text at every stage of dating to build attraction and secure the date", whyTrending: "Texting anxiety is one of the top dating concerns for men 18-35", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Relationships", emoji: "📱" },
  { title: "Healing from a Narcissist", description: "Step-by-step recovery guide for survivors of narcissistic relationships", whyTrending: "Narcissism content has 20B+ TikTok views — massive healing product demand", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Relationships", emoji: "🌱" },
  { title: "High-Value Woman Blueprint", description: "Mindset, boundaries and attraction standards that attract quality relationships", whyTrending: "High-value woman content dominates relationship niche with billions of views", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Relationships", emoji: "💎" },

  // ── PARENTING ─────────────────────────────────────────────────────────────
  { title: "Toddler Sleep Training Guide", description: "Gentle and cry-it-out methods explained for parents struggling with sleep", whyTrending: "Sleep deprivation is every new parent's nightmare — products sell on desperation", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Parenting", emoji: "🍼" },
  { title: "Screen Time Solutions for Kids", description: "Replace screen time with engaging activities and build healthy tech habits", whyTrending: "Screen addiction is parents' #1 concern per surveys in 2024-2025", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Parenting", emoji: "📵" },
  { title: "Raising Confident Kids", description: "Evidence-based parenting strategies for raising emotionally intelligent children", whyTrending: "Mental health awareness driving demand for proactive parenting guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Parenting", emoji: "🌟" },
  { title: "ADHD at Home Success System", description: "Practical tools and routines for parents of children with ADHD", whyTrending: "ADHD diagnoses up 400% — parents overwhelmed and seeking practical help", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Parenting", emoji: "🎯" },

  // ── FOOD & NUTRITION ──────────────────────────────────────────────────────
  { title: "Intermittent Fasting Blueprint", description: "Science-backed IF protocols for weight loss, energy and longevity", whyTrending: "IF still one of the top searched diets globally — perennial demand", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "⏰" },
  { title: "Anti-Inflammatory Meal Plan", description: "28-day meal plan with recipes to reduce inflammation and chronic pain", whyTrending: "Inflammation linked to every major disease — demand for diet solutions massive", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Food & Nutrition", emoji: "🥗" },
  { title: "Protein-Packed Meal Prep Guide", description: "High-protein, budget-friendly meal prep for muscle building and fat loss", whyTrending: "Protein macro tracking viral on social media — meal prep content top-performing", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "🍗" },
  { title: "Gut-Friendly Recipes Cookbook", description: "50 delicious recipes for healing IBS, bloating and digestive disorders", whyTrending: "Gut microbiome research creating enormous interest in gut-healing foods", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "🥦" },
  { title: "Nigerian Food & Wellness Guide", description: "Traditional Nigerian superfoods and recipes for modern health goals", whyTrending: "African diaspora massive and underserved — cultural health content converts well", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "🍲" },
  { title: "Keto for Women Over 40", description: "Keto diet modified for female hormones and metabolism after 40", whyTrending: "Generic keto guides don't address women's needs — massive gap in market", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Food & Nutrition", emoji: "🥑" },
  { title: "Smoothie Bible for Weight Loss", description: "100 fat-burning smoothie recipes with specific health benefits", whyTrending: "Smoothie content gets hundreds of millions of views monthly", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "🥤" },

  // ── HOME & LIFESTYLE ──────────────────────────────────────────────────────
  { title: "Clean Home Detox Guide", description: "Replace 50 toxic household products with cheap safe DIY alternatives", whyTrending: "Non-toxic living TikTok trend driving massive demand for chemical-free home guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "🏡" },
  { title: "Minimalist Living Blueprint", description: "How to declutter your home and life using the Japanese minimalism method", whyTrending: "KonMari and minimalism content sees perennial viral spikes", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "✨" },
  { title: "Homesteading Beginners Guide", description: "Start a sustainable backyard garden, raise chickens and live more self-sufficiently", whyTrending: "Food security anxiety post-pandemic driving homesteading interest through the roof", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Home & Lifestyle", emoji: "🌻" },
  { title: "Essential Oils for Every Ailment", description: "Complete guide to using essential oils for health, cleaning and mood", whyTrending: "Essential oil market at $12B — buyers want DIY guide instead of paying MLMs", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "🌹" },
  { title: "Manifestation & Law of Attraction", description: "Practical daily rituals and scripting techniques for goal manifestation", whyTrending: "Manifestation content has 50B+ views — digital workbooks sell extremely fast", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "🌙" },
  { title: "Budget Home Makeover Guide", description: "Transform any room on a $200 budget using DIY and thrift flipping", whyTrending: "Home improvement content exploding as people stay home more and inflation rises", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "🛋️" },

  // ── HAIR & BEAUTY ─────────────────────────────────────────────────────────
  { title: "Natural Hair Growth Secrets", description: "Home remedies and hair care routines for faster, thicker hair growth", whyTrending: "Hair loss affecting 80M Americans — natural solutions market exploding", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Hair & Beauty", emoji: "💇" },
  { title: "Natural Hair Care Bible for Black Women", description: "Complete curl pattern, protective styling and moisture retention guide", whyTrending: "Massive underserved natural hair market with passionate spending community", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Hair & Beauty", emoji: "👸" },
  { title: "Castor Oil Miracle Guide", description: "Every beauty and health use of castor oil for hair, skin, lashes and more", whyTrending: "Castor oil videos get 100M+ views regularly — product demand enormous", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Hair & Beauty", emoji: "🌿" },
  { title: "Glow Up Guide: 90 Days", description: "Complete beauty, fitness and style transformation plan for total glow up", whyTrending: "Glow up content viral with Gen Z — transformation guides extremely popular", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Hair & Beauty", emoji: "✨" },
  { title: "Reverse Aging Skincare Protocol", description: "Science-backed anti-aging skincare routines using affordable products", whyTrending: "Anti-aging industry at $67B — people want expert guide without paying dermatologist fees", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Hair & Beauty", emoji: "⏳" },

  // ── SPIRITUALITY & MINDSET ────────────────────────────────────────────────
  { title: "333 Affirmations for Abundance", description: "Powerful daily affirmations organized by wealth, health, love and purpose", whyTrending: "Affirmation content consistently viral — digital affirmation guides sell easily", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 7, category: "Spirituality", emoji: "🙏" },
  { title: "Spiritual Awakening Guide", description: "Navigate your spiritual awakening journey with clarity and without confusion", whyTrending: "Spiritual awakening searches up 340% — millions going through the process", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Spirituality", emoji: "🌟" },
  { title: "Vision Board Workbook 2025", description: "Complete system for creating powerful vision boards and making them work", whyTrending: "New Year goal setting drives massive annual demand — vision board content viral", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Spirituality", emoji: "🎯" },
  { title: "Astrology Money Guide", description: "How to use your birth chart to align financial decisions with cosmic cycles", whyTrending: "Astrology market at $12.8B and growing — financial astrology is newest trend", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Spirituality", emoji: "⭐" },

  // ── PRODUCTIVITY & BUSINESS ───────────────────────────────────────────────
  { title: "Notion Setup for Life Organization", description: "Complete Notion workspace for business, life goals, and productivity", whyTrending: "Notion has 30M users all searching for setup guides and templates", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Productivity", emoji: "📋" },
  { title: "Email List Building from Zero", description: "Grow an email list of 10,000 subscribers who actually buy from you", whyTrending: "Creators discovering social media followers don't equal sales — email list crucial", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Productivity", emoji: "📧" },
  { title: "Launch Your Online Course Guide", description: "How to package your knowledge into a profitable online course in 30 days", whyTrending: "Online learning market at $400B — new creators entering in massive numbers", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Productivity", emoji: "🎓" },
  { title: "Client Attraction System for Coaches", description: "How coaches and consultants get 5-10 new clients/month using organic content", whyTrending: "Coaching industry at $20B — massive new coaches need client acquisition help", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Productivity", emoji: "📣" },
  { title: "Batch Content Creation System", description: "How to create 30 days of content in one afternoon using AI and templates", whyTrending: "Content creation burnout epidemic — systematized content batching highly demanded", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Productivity", emoji: "⚡" },
  { title: "Work From Home Productivity Bible", description: "Systems and environment setup for maximum focus working from home", whyTrending: "80M+ remote workers struggling with WFH productivity — demand huge", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Productivity", emoji: "🏠" },

  // ── KIDS & EDUCATION ──────────────────────────────────────────────────────
  { title: "Homeschooling Starter Guide", description: "Complete framework for parents new to homeschooling with curriculum picks", whyTrending: "Homeschooling grew 300% post-pandemic and plateaued at new high — permanent market", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Education", emoji: "📚" },
  { title: "Teach Kids Money at Any Age", description: "Age-appropriate financial lessons and activities for raising money-smart kids", whyTrending: "Financial literacy gap causing generational money problems — parents desperate", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Education", emoji: "🎒" },
  { title: "Kids Mindfulness Activity Book", description: "40 mindfulness exercises designed specifically for children aged 4-12", whyTrending: "Kids mental health crisis — parents willing to pay for tools that help", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Education", emoji: "🎈" },

  // ── PET CARE ──────────────────────────────────────────────────────────────
  { title: "Dog Health Home Remedies", description: "Natural treatments for common dog ailments to save vet bills", whyTrending: "Average vet bill over $1,500 — dog owners desperate for home treatment guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Pet Care", emoji: "🐕" },
  { title: "Dog Training in 21 Days", description: "Positive reinforcement training for the 10 most common behavior problems", whyTrending: "Pet adoption surge created million of undertrained dogs and overwhelmed owners", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Pet Care", emoji: "🐾" },
  { title: "Raw Dog Food Complete Guide", description: "How to safely feed your dog a raw diet for health, longevity and vitality", whyTrending: "Raw feeding movement going viral — processed pet food distrust growing fast", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Pet Care", emoji: "🥩" },

  // ── PREGNANCY & FERTILITY ─────────────────────────────────────────────────
  { title: "Natural Fertility Boosting Guide", description: "Diet, lifestyle and supplement protocols for women struggling to conceive", whyTrending: "Fertility rates declining globally — natural fertility content gets massive traffic", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Women's Health", emoji: "🤱" },
  { title: "Pregnancy Nutrition Blueprint", description: "Trimester-by-trimester nutrition plan for healthy mom and baby", whyTrending: "4M pregnancies annually in US alone — highly captive, motivated audience", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Women's Health", emoji: "🌸" },
  { title: "PCOS Natural Management Guide", description: "Dietary and lifestyle interventions that reverse PCOS symptoms naturally", whyTrending: "PCOS affects 1 in 10 women — massively underserved with expensive medication-only options", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Women's Health", emoji: "💜" },

  // ── TRAVEL & LIFESTYLE ────────────────────────────────────────────────────
  { title: "Travel Hacking Beginners Bible", description: "How to fly business class and stay in luxury hotels for free using points", whyTrending: "Revenge travel post-pandemic — travel hacking demand at 10-year high", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Travel", emoji: "✈️" },
  { title: "Become a Digital Nomad Guide", description: "How to leave your job and work remotely from anywhere in the world", whyTrending: "Remote work normalization making digital nomad lifestyle achievable for millions", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Travel", emoji: "🌍" },
  { title: "Budget Travel Europe on $50/Day", description: "How to explore all of Europe spending under $50 per day total", whyTrending: "Inflation making people seek budget travel alternatives — massive search volume", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Travel", emoji: "🗺️" },

  // ── CAREER & PROFESSIONAL ─────────────────────────────────────────────────
  { title: "LinkedIn Profile to Job in 30 Days", description: "Profile optimization and outreach strategy that gets job offers fast", whyTrending: "Job market tightening — professionals desperate for LinkedIn advantage", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Career", emoji: "💼" },
  { title: "Salary Negotiation Scripts", description: "Word-for-word scripts and strategies to get 20-40% salary increases", whyTrending: "Wage gap awareness driving demand for negotiation education", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Career", emoji: "💰" },
  { title: "Nurse Side Hustle Guide", description: "How healthcare workers make extra $2,000-$5,000/month outside clinical hours", whyTrending: "Nurse burnout epidemic — 4.3M nurses seeking additional income streams", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Career", emoji: "🏥" },
  { title: "Teacher Side Hustle Bible", description: "How teachers make 6-figure side incomes selling lesson plans and courses", whyTrending: "Teachers Marketplace is a proven revenue source — new teachers need guidance", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Career", emoji: "📖" },
  { title: "Virtual Assistant Launch Guide", description: "Land your first VA client in 7 days and scale to $5,000/month", whyTrending: "VA demand from solopreneurs exploding — easiest remote work to start", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Career", emoji: "💻" },
  { title: "Social Media Manager Quick Start", description: "Get your first 3 social media management clients and earn $3-5K/month", whyTrending: "Every business needs social media — skilled managers in massive demand", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Career", emoji: "📱" },

  // ── ADDITIONAL NICHE LEADERS ──────────────────────────────────────────────
  { title: "Chakra Healing Workbook", description: "7-chakra healing guide with affirmations, exercises and crystal recommendations", whyTrending: "Chakra content viral on Instagram and TikTok — healing community buying heavily", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Spirituality", emoji: "🔮" },
  { title: "Plant Medicine Beginner Guide", description: "Introduction to medicinal plants, adaptogen herbs and natural healing protocols", whyTrending: "Herbalism and plant medicine growing 35% annually — beginner market huge", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "🌿" },
  { title: "Aloe Vera: 75 Home Uses", description: "Complete guide to growing and using aloe vera for skin, gut, and immunity", whyTrending: "Aloe content consistently viral — cheap, accessible, high-value guide topic", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🌱" },
  { title: "Eczema & Psoriasis Natural Guide", description: "Dietary and topical natural protocols to dramatically reduce flare-ups", whyTrending: "100M+ eczema sufferers — medical system offers steroids only — natural gap massive", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Health & Home Remedies", emoji: "🌿" },
  { title: "Sourdough Bread Baking Guide", description: "Complete beginner to advanced sourdough baking with troubleshooting", whyTrending: "Sourdough baking community has 50M+ enthusiasts globally who buy guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "🍞" },
  { title: "Cold Plunge & Ice Bath Protocol", description: "Beginner to advanced cold therapy protocols for recovery, fat loss and mood", whyTrending: "Wim Hof and ice bath culture exploding — millions adopting cold therapy", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "🧊" },
  { title: "Sauna Healing Guide", description: "Health benefits, protocols and home sauna setup for detox and longevity", whyTrending: "Home sauna installations up 200% — buyers want an expert guide", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🔥" },
  { title: "Red Light Therapy at Home", description: "How to use affordable red light devices for pain, skin, and sleep", whyTrending: "Red light therapy going mainstream — consumers buying devices need protocols", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "🔴" },
  { title: "Cycle Syncing Guide for Women", description: "Align workouts, diet and work schedule with your monthly cycle for peak performance", whyTrending: "Cycle syncing content breaking records on TikTok — women actively seeking this", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Women's Health", emoji: "🌙" },
  { title: "Dry Fasting & Extended Fasting Guide", description: "Advanced fasting protocols for accelerated healing, autophagy and spiritual clarity", whyTrending: "Fasting community growing rapidly — advanced protocols have high paying audience", monetizationPotential: "High", difficulty: "Hard", suggestedPrice: 37, category: "Health & Home Remedies", emoji: "⚡" },
  { title: "Parasite Cleanse Protocol", description: "Natural anti-parasitic herbs, protocols and foods for gut cleansing", whyTrending: "Parasite cleanse topic went mega-viral on TikTok — millions searching protocols", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "🧬" },
  { title: "Grounding & Earthing Guide", description: "Proven grounding techniques and protocols for reducing chronic inflammation", whyTrending: "Earthing/grounding content going viral — people seeking affordable healing", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Health & Home Remedies", emoji: "🌍" },
  { title: "Fertility Diet & Egg Quality Guide", description: "Research-backed nutrition plan to improve egg quality in 90 days", whyTrending: "Egg freezing and IVF costs pushing women toward natural fertility optimization", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Women's Health", emoji: "🥚" },
  { title: "Biohacking for Beginners", description: "Accessible biohacking protocols for improved energy, sleep and cognitive performance", whyTrending: "Biohacking mainstream now — millions wanting to optimize without complicated tech", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Health & Home Remedies", emoji: "🧬" },
  { title: "Testosterone Boost Natural Guide", description: "Natural diet, exercise and lifestyle strategies to optimize testosterone", whyTrending: "Male testosterone declining 1% per year — men urgently seeking solutions", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Men's Health", emoji: "💪" },
  { title: "Men's Mental Health Workbook", description: "Practical emotional intelligence and mental health tools written specifically for men", whyTrending: "Men's mental health awareness exploding — stigma reducing and demand rising", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Men's Health", emoji: "🧠" },
  { title: "African American Hair Growth System", description: "Proven growth strategies, protective styles and moisture retention for Type 4 hair", whyTrending: "Natural hair movement strong and growing — specialized guide commands premium price", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Hair & Beauty", emoji: "✊" },
  { title: "Lash Growth & Eye Care Guide", description: "Natural oils and routines for longer, fuller lashes without extensions", whyTrending: "Lash extension market shifting to natural growth — DIY guides trending", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Hair & Beauty", emoji: "👁️" },
  { title: "Acne Natural Cure Protocol", description: "Gut-skin connection approach and topical protocols to permanently clear acne", whyTrending: "Acne affects 85% of people — natural/holistic approach massively searched", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Health & Home Remedies", emoji: "✨" },

  // ── TECH & AI TOOLS ───────────────────────────────────────────────────────
  { title: "Prompt Engineering Bible", description: "Master ChatGPT, Claude and Gemini prompts to 10x your productivity in any field", whyTrending: "AI tools mainstream — users desperate for prompts that actually work", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🤖" },
  { title: "No-Code App Builder Masterclass", description: "Build and launch a web app with Bubble, Webflow or Glide — no coding required", whyTrending: "No-code revolution enabling non-technical founders — massive growing market", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "💻" },
  { title: "AI Tools for Entrepreneurs", description: "50 AI tools that replace employees and save 40 hours/week in your business", whyTrending: "Business owners replacing staff with AI — need curated guide to best tools", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Productivity", emoji: "⚡" },
  { title: "Notion Templates Business Bundle", description: "20 plug-and-play Notion templates for CRM, projects, finance and content planning", whyTrending: "Notion has 35M+ users and template demand exploding on Etsy and Gumroad", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 47, category: "Productivity", emoji: "📋" },
  { title: "ChatGPT Side Business Playbook", description: "7 online businesses you can start this week using nothing but ChatGPT and a laptop", whyTrending: "AI side hustle content going viral — action-oriented guides sell best", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🤖" },
  { title: "Midjourney & AI Art Income Guide", description: "Sell AI-generated art, book covers, and digital prints for passive income", whyTrending: "AI art market exploding — creators monetizing on Etsy making $5K+/month", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🎨" },
  { title: "Make Money with AI Automation", description: "Build automated income streams using Zapier, Make.com and AI without coding", whyTrending: "Automation income stories viral on YouTube — people want the exact systems", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "⚙️" },

  // ── PHOTOGRAPHY & CONTENT CREATION ───────────────────────────────────────
  { title: "Mobile Photography Pro Guide", description: "Shoot professional-quality photos with just your iPhone or Android camera", whyTrending: "Everyone has a smartphone — content creator market at 50M+ and growing", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Productivity", emoji: "📸" },
  { title: "Lightroom Preset Collection + Tutorial", description: "25 professional presets with step-by-step editing tutorial for stunning photos", whyTrending: "Photo editing content massive — presets sell millions of units annually", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🌅" },
  { title: "Faceless Content Creation Blueprint", description: "Build a profitable content business without ever showing your face or voice", whyTrending: "Privacy-conscious creators driving massive demand for faceless strategies", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🎭" },
  { title: "UGC Creator Starter Kit", description: "How to land $500-2,000/month brand deals creating user-generated content", whyTrending: "UGC creator market exploded 300% — brands pay $200-1,000 per video", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 37, category: "Make Money Online", emoji: "📱" },
  { title: "Podcast Launch in 7 Days", description: "Complete step-by-step system to launch a profitable podcast from zero", whyTrending: "Podcast market growing 20% annually — ad revenue at $4B and growing", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🎙️" },

  // ── REAL ESTATE & PROPERTY ────────────────────────────────────────────────
  { title: "House Flipping for Beginners", description: "Step-by-step guide to finding, financing and flipping your first property", whyTrending: "HGTV effect permanent — real estate flipping content consistently viral", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Personal Finance", emoji: "🏚️" },
  { title: "Airbnb Hosting Mastery Guide", description: "How to optimize your Airbnb listing and earn $3,000-$8,000/month", whyTrending: "Short-term rental income is top searched passive income idea globally", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 37, category: "Make Money Online", emoji: "🏡" },
  { title: "Real Estate Investing with $10K", description: "How to start building a property portfolio with a small starting budget", whyTrending: "High home prices making people seek alternative entry points to real estate", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Personal Finance", emoji: "🏠" },
  { title: "BRRRR Strategy Complete Guide", description: "Buy, Rehab, Rent, Refinance, Repeat — the ultimate real estate wealth formula", whyTrending: "BRRRR is the most searched real estate strategy among new investors", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Personal Finance", emoji: "🔄" },

  // ── SOCIAL MEDIA GROWTH ───────────────────────────────────────────────────
  { title: "Pinterest Traffic Machine", description: "Drive 100,000+ monthly visitors to your blog or shop using Pinterest SEO", whyTrending: "Pinterest organic reach still massive — free traffic goldmine few exploit", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Productivity", emoji: "📌" },
  { title: "YouTube Shorts Growth Blueprint", description: "Get 10K+ subscribers in 90 days using viral Shorts strategies", whyTrending: "YouTube Shorts paying $0.05-$0.07 per 1000 views — creators rushing to platform", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "📹" },
  { title: "Twitter/X Growth & Monetization", description: "Grow to 10K followers and earn from subscriptions, affiliate and X Ads", whyTrending: "X monetization open to creators with 500+ subscribers — huge opportunity", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Make Money Online", emoji: "✖️" },
  { title: "Facebook Group Monetization Bible", description: "Build a thriving Facebook group and turn it into $5,000+/month business", whyTrending: "Facebook Groups still #1 community platform — monetization methods evolving", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "👥" },
  { title: "LinkedIn B2B Lead Generation System", description: "Automated outreach and content strategy to generate $10K+/month in B2B clients", whyTrending: "LinkedIn most effective B2B platform — demand for lead gen guides enormous", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Career", emoji: "💼" },
  { title: "TikTok Shop Affiliate Playbook", description: "Earn $3,000-$10,000/month promoting products via TikTok Shop affiliate program", whyTrending: "TikTok Shop affiliates earning more than traditional influencers with no inventory", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 37, category: "Make Money Online", emoji: "🛍️" },

  // ── GAMING & STREAMING ────────────────────────────────────────────────────
  { title: "Twitch Streaming Success Blueprint", description: "Grow to 50+ concurrent viewers and monetize your Twitch channel from day one", whyTrending: "Gaming creator market at $250B — streaming accessible to everyone now", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🎮" },
  { title: "Gaming YouTube Channel Growth Guide", description: "Build a gaming channel to 100K subscribers with a strategic content roadmap", whyTrending: "Gaming content is the #1 entertainment category — creator income huge", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🕹️" },
  { title: "Sell Gaming Guides on Etsy", description: "Create and sell game guides, coaching packages and strategy PDFs profitably", whyTrending: "Gamers pay premium for walkthroughs — digital download model scales infinitely", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Make Money Online", emoji: "⚔️" },

  // ── ENVIRONMENT & SUSTAINABILITY ──────────────────────────────────────────
  { title: "Zero Waste Home Guide", description: "How to reduce household waste by 90% and save $2,000/year in the process", whyTrending: "Gen Z environmental values driving sustainable living content virality", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "♻️" },
  { title: "Sustainable Business Blueprint", description: "How to start and market an eco-friendly product business profitably", whyTrending: "Green business market growing 20% annually — consumers paying premium for sustainable", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "🌱" },
  { title: "Urban Gardening & Food Forest Guide", description: "Grow $3,000 worth of food per year in a small urban backyard or balcony", whyTrending: "Food inflation + homesteading trend driving urban gardening interest to all-time high", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "🌿" },

  // ── MUSIC & AUDIO ─────────────────────────────────────────────────────────
  { title: "Beat Making for Beginners", description: "Create professional hip-hop and trap beats at home using free software", whyTrending: "Music production accessible now — beats sell for $20-$500 each online", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Make Money Online", emoji: "🎵" },
  { title: "Music Licensing Passive Income Guide", description: "License your music on Pond5, AudioJungle and Musicbed for royalty income", whyTrending: "Content creators need licensed music — passive royalty income model proven", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Make Money Online", emoji: "🎸" },
  { title: "Voice Acting Freelancing Launchpad", description: "Land $2,000-$8,000/month voice acting gigs from home with no experience", whyTrending: "AI audio surge creating demand for authentic human voice actors", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 37, category: "Career", emoji: "🎤" },

  // ── SPORTS & OUTDOOR ──────────────────────────────────────────────────────
  { title: "Trail Running Training Plan", description: "12-week plan to run your first trail marathon or ultra regardless of age", whyTrending: "Trail running grew 230% — outdoor fitness movement permanent post-pandemic", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "🏃" },
  { title: "Pickleball Beginner to Pro Guide", description: "Master pickleball fundamentals and strategy to win matches faster", whyTrending: "Pickleball is the fastest-growing sport in America — 36M players in 2025", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Fitness & Body", emoji: "🏓" },
  { title: "Home Gym Build Guide Under $500", description: "Build an effective home gym on a budget with the right equipment picks", whyTrending: "Home fitness permanent trend — people canceling gym memberships in record numbers", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Fitness & Body", emoji: "🏋️" },
  { title: "Cycling for Weight Loss Plan", description: "12-week outdoor and indoor cycling plan for serious fat loss and fitness", whyTrending: "Cycling market at record highs — riders seeking structured programs", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "🚴" },

  // ── LEGAL & BUSINESS PROTECTION ───────────────────────────────────────────
  { title: "Freelancer Legal Protection Kit", description: "Contracts, NDAs and legal frameworks every freelancer needs to protect income", whyTrending: "70M US freelancers operating without proper legal protection — massive risk", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Career", emoji: "⚖️" },
  { title: "LLC Formation & Business Setup Guide", description: "How to legally form your LLC, open business bank accounts and protect assets", whyTrending: "Small business formation at record highs — owners need plain-English guidance", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 37, category: "Make Money Online", emoji: "📄" },
  { title: "Intellectual Property Protection Guide", description: "Trademark, copyright and patent basics for online creators and entrepreneurs", whyTrending: "Creator economy theft rampant — creators desperate for IP protection knowledge", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 27, category: "Make Money Online", emoji: "™️" },

  // ── RELATIONSHIP & DATING ─────────────────────────────────────────────────
  { title: "Divorce Recovery Roadmap for Women", description: "Financial, emotional and legal steps to rebuild confidently after divorce", whyTrending: "42% of marriages end in divorce — massive underserved recovery guide market", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Relationships", emoji: "🦋" },
  { title: "Attachment Style Healing Guide", description: "Identify and heal anxious, avoidant or disorganized attachment patterns", whyTrending: "Attachment style content at 3B+ TikTok views — healing guides in high demand", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Relationships", emoji: "💞" },
  { title: "Boundaries Masterclass for People Pleasers", description: "Set firm boundaries at work and in relationships without guilt or conflict", whyTrending: "People-pleasing content viral with 10B+ views — boundary-setting is top searched topic", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Mental Health & Wellness", emoji: "🛡️" },
  { title: "Dating After 40 Success Blueprint", description: "Modern dating strategies specifically for mature singles re-entering the dating world", whyTrending: "40M+ singles over 40 in US — this demographic underserved by mainstream dating advice", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Relationships", emoji: "💏" },

  // ── ADDITIONAL HIGH-VALUE NICHES ──────────────────────────────────────────
  { title: "Meal Prep for Muscle & Fat Loss", description: "4-week meal prep system with macros, shopping lists and prep instructions", whyTrending: "Meal prep content top-performing across all fitness platforms globally", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "🥡" },
  { title: "Vegan on a Budget Cookbook", description: "100 cheap, delicious vegan meals for under $5 per serving", whyTrending: "Plant-based diet growing 300% — budget-conscious vegans seeking affordable guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Food & Nutrition", emoji: "🥬" },
  { title: "Senior Fitness Program 60+", description: "Safe, effective strength and mobility exercises designed specifically for seniors", whyTrending: "73M baby boomers entering senior years — enormous untapped fitness market", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Fitness & Body", emoji: "👴" },
  { title: "Kids Coding Introduction Guide", description: "Teach children ages 6-12 to code with fun projects and simple explanations", whyTrending: "Parent demand for STEM education through coding at all-time high", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Education", emoji: "👨‍💻" },
  { title: "Small Dog Training Bible", description: "Specific techniques for training small and toy breeds with their unique challenges", whyTrending: "Small dogs most popular pet segment — owners frustrated generic training doesn't work", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Pet Care", emoji: "🐩" },
  { title: "Cat Behavioral Problems Solved", description: "Fix scratching, biting, litter box issues and aggression in domestic cats", whyTrending: "Cat ownership at record high — behavior problems #1 reason cats surrendered", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Pet Care", emoji: "🐱" },
  { title: "Couples Money Workbook", description: "Joint budgeting system and financial exercises for couples to build wealth together", whyTrending: "Money is #1 cause of divorce — couples seeking financial alignment tools", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Personal Finance", emoji: "💑" },
  { title: "Solo Travel Safety & Adventure Guide", description: "How to travel the world alone safely and affordably as a modern explorer", whyTrending: "Solo travel up 240% post-pandemic — especially women travelers seeking guidance", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Travel", emoji: "🌍" },
  { title: "Remote Work Abroad Visa Guide", description: "Digital nomad visas, tax strategies and relocation guides for 30+ countries", whyTrending: "75+ countries now offer digital nomad visas — huge demand for consolidated guide", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Travel", emoji: "🛂" },
  { title: "Burn-Out Recovery System", description: "Evidence-based recovery protocol for chronic burnout in professionals", whyTrending: "Burnout affected 77% of workers in 2024 — desperate market for structured recovery", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Mental Health & Wellness", emoji: "🔋" },
  { title: "Grief Healing Journal", description: "Guided prompts and healing exercises for processing loss and moving forward", whyTrending: "Post-pandemic grief crisis creating huge demand for structured healing tools", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Mental Health & Wellness", emoji: "🌈" },
  { title: "Autism Parent Survival Guide", description: "Practical daily strategies, therapies and resources for parents of autistic children", whyTrending: "Autism diagnoses up 178% — parents overwhelmed and underserved by generic resources", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Parenting", emoji: "🧩" },
  { title: "Homeschool Curriculum for Gifted Kids", description: "Accelerated learning programs and activities for gifted children at home", whyTrending: "Gifted child programs cut from schools — parents taking education into own hands", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Education", emoji: "🌟" },
  { title: "Black Entrepreneurship Blueprint", description: "Funding sources, networks and strategies specifically for Black-owned businesses", whyTrending: "Black business ownership growing 30% — community seeking targeted resources", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "✊" },
  { title: "Immigrant Business Success Guide", description: "How immigrants build thriving businesses and navigate US business systems", whyTrending: "Immigrants start 55% of US billion-dollar companies — massive aspirational market", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 37, category: "Make Money Online", emoji: "🗺️" },
  { title: "Student Loan Payoff Strategy", description: "Aggressive repayment plans and forgiveness strategies for crushing student debt", whyTrending: "$1.7T in student debt — millions searching for strategic payoff guidance", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Personal Finance", emoji: "🎓" },
  { title: "Side Hustle to Business Transition Guide", description: "How to leave your 9-5 and turn your side hustle into a full-time business", whyTrending: "The Great Resignation permanent — people planning exits need strategic guide", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Make Money Online", emoji: "🚀" },
  { title: "Copywriting Crash Course", description: "Write high-converting sales pages, emails and ads that make money", whyTrending: "Copywriting is the highest-paid freelance skill — demand massively exceeds supply", monetizationPotential: "High", difficulty: "Medium", suggestedPrice: 47, category: "Career", emoji: "✍️" },
  { title: "Wedding Planning on a Budget", description: "Plan your dream wedding for under $5,000 without sacrificing the experience", whyTrending: "Average wedding cost $35K — budget brides searching for alternatives relentlessly", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 17, category: "Home & Lifestyle", emoji: "💍" },
  { title: "DIY Home Repairs Bible", description: "Fix 50 common home problems yourself and save $10,000+ in contractor fees", whyTrending: "Contractor costs skyrocketed — homeowners forced to DIY and need trusted guides", monetizationPotential: "High", difficulty: "Easy", suggestedPrice: 27, category: "Home & Lifestyle", emoji: "🔧" },
];

function seededShuffle<T>(arr: T[], seed: number): T[] {
  const a = [...arr];
  let s = (seed >>> 0) || 1;
  for (let i = a.length - 1; i > 0; i--) {
    s = Math.imul(s ^ (s >>> 15), 0x45d9f3b) >>> 0;
    s = Math.imul(s ^ (s >>> 13), 0x9e3779b9) >>> 0;
    const j = s % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

router.get("/trending/ideas", requireAuth, async (req: any, res) => {
  try {
    const difficulty = req.query.difficulty as string | undefined;
    const uid = req.userId ?? 0;
    const seed = typeof uid === "number"
      ? uid
      : String(uid).split("").reduce((a: number, c: string) => (a * 31 + c.charCodeAt(0)) | 0, 7);

    const combined = [...ALL_IDEAS, ...ALL_TRENDING_IDEAS];
    let ideas = seededShuffle(combined, seed);
    if (difficulty && ["Easy", "Medium", "Hard"].includes(difficulty)) {
      ideas = ideas.filter((i: any) => i.difficulty === difficulty);
    }
    res.json({ ideas, total: combined.length });
  } catch (err) {
    req.log.error({ err }, "TrendingIdeas error");
    res.status(500).json({ error: "Failed to fetch trending ideas" });
  }
});

router.get("/trending/refresh", requireAuth, async (_req, res) => {
  res.json({ message: "Ideas refreshed" });
});

export default router;
