export const HOOKS: Record<string, string[]> = {
  youtube: [
    "Nobody talks about this — and honestly, that silence is the whole problem.",
    "I'm about to say something most people will push back on. That's fine.",
    "Three years of getting this wrong taught me one thing nobody warned me about.",
    "This is the video I wish existed when I first started down this road.",
    "The conventional approach to this has a flaw most people never notice — until it's obvious.",
    "Here's the uncomfortable truth that finally clicked for me — and I can't un-know it.",
    "The top 1% approach {TOPIC} completely differently. It's not talent. It's not luck.",
    "I've done the research, run the experiments, made the mistakes. Here's what actually matters.",
    "Stop me if this sounds familiar...",
    "There's a reason most people stay stuck. And it's not what anyone talks about online.",
    "I almost quit. I'm glad I didn't. Here's what changed everything.",
    "The thing about {TOPIC} that people get wrong from day one.",
    "This changed how I think about {TOPIC} permanently.",
    "Before we get into this — I need you to forget everything you think you know.",
    "Real talk: the advice you've been following might be the exact thing holding you back.",
    "I spent months trying to figure this out so you don't have to.",
    "Here's what nobody tells you at the beginning.",
    "Every person who's ever succeeded at this had one moment that shifted everything.",
    "The question isn't whether this works. The question is why so few people actually do it.",
    "Let's cut through everything and get to what actually matters.",
  ],
  storytelling: [
    "It was 2 a.m. when it finally hit me.",
    "The moment everything changed wasn't dramatic. It was quiet — almost embarrassingly small.",
    "I remember the exact feeling. The specific weight of it.",
    "Nobody warned me it would feel like this.",
    "There's a version of this story where everything works out immediately. This isn't that version.",
    "I've thought about this moment more times than I can count.",
    "It started, as most important things do, with a question I couldn't answer.",
    "The day I made that decision, I had no idea what I was actually choosing.",
    "She said one sentence, and I've never forgotten it.",
    "Some lessons arrive gently. Others arrive like a wall you didn't see.",
    "There was a before. And then there was after. The dividing line was smaller than I expected.",
    "I used to think I understood. Then I was wrong in the most instructive way possible.",
    "The thing about {TOPIC} is — it doesn't announce itself. It just quietly rearranges everything.",
    "I can point to the exact week it all shifted.",
    "For a long time I got this wrong. And I was completely convinced I was right.",
  ],
  persuasive: [
    "You already know something isn't working. That's why you're here.",
    "Most people settle. You don't have to — and deep down you know that.",
    "The gap between where you are and where you want to be isn't skill. It's one decision.",
    "Here's what separates people who get results from people who just learn about results.",
    "You've probably tried the standard approach. This isn't that.",
    "What if the only thing standing between you and what you want is the right framework?",
    "Let me ask you something most people are afraid to ask themselves.",
    "The reason it hasn't worked isn't you. It's the approach.",
    "Everything you need to make this work is closer than you think.",
    "There's a reason some people get this right on the first try. It's not random.",
    "Stop wasting time on strategies that were never designed for someone in your position.",
    "The solution to {TOPIC} isn't more effort. It's more precision.",
    "What if the core assumption everyone's working from is the actual problem?",
    "I'm going to show you the exact approach — not the theory, the actual process.",
    "Most advice on this is wrong. Not slightly off — fundamentally backward.",
  ],
  conversational: [
    "Okay, so here's the thing about {TOPIC} that nobody actually says out loud.",
    "Can we just be honest for a second?",
    "I've been thinking about {TOPIC} a lot lately and I can't stop coming back to this.",
    "This might be controversial but I need to say it.",
    "Real question — when did {TOPIC} become so overcomplicated?",
    "You know that feeling when something just... clicks? That's what this is.",
    "I want to talk about something that most people brush past too quickly.",
    "Hear me out — because this might sound counterintuitive at first.",
    "Here's what I've noticed, and I think it's worth talking about.",
    "Let me tell you exactly what changed my mind on this.",
    "I used to think the same thing. And then I actually looked at the data.",
    "The more I dig into {TOPIC}, the more I keep finding the same thing.",
    "Something shifted for me recently. And I want to share it.",
    "This is going to sound simple. Most powerful things do.",
    "I keep having the same conversation with people about {TOPIC}. Let me just write it down.",
  ],
  professional: [
    "The conventional wisdom on {TOPIC} deserves scrutiny — and the evidence warrants it.",
    "Three factors consistently differentiate high-performing outcomes in this area.",
    "What the data reveals about {TOPIC} challenges several widely-held assumptions.",
    "The organizations navigating {TOPIC} most effectively share one critical characteristic.",
    "Most frameworks for approaching {TOPIC} optimize for the wrong variable.",
    "A closer examination of {TOPIC} reveals patterns that carry significant implications.",
    "The question is no longer whether {TOPIC} matters — it's how to approach it strategically.",
    "What separates sophisticated practitioners from beginners is not knowledge — it's application.",
    "Understanding {TOPIC} at a structural level reveals the leverage points most people miss.",
    "The evidence points in one direction. The challenge is applying it consistently.",
    "Let's be precise about what {TOPIC} actually requires — not what it's assumed to require.",
    "The most durable competitive advantage in {TOPIC} comes from clarity, not complexity.",
    "Senior practitioners think about {TOPIC} differently. Here's where the divergence begins.",
    "There's a framework for approaching {TOPIC} that consistently outperforms the alternatives.",
    "The critical insight most people arrive at too late.",
  ],
  poetic: [
    "There's a kind of ache that lives in the space between knowing and doing.",
    "{TOPIC} has always been more than what it appears on the surface.",
    "Some things can't be explained — only felt, and then slowly understood.",
    "The most important truths tend to arrive without fanfare.",
    "There's a language beneath language — and {TOPIC} speaks it fluently.",
    "Not everything worth understanding can be reduced to a list.",
    "What I love most about {TOPIC} is what it reveals about us.",
    "Every deep thing is also, at its core, a simple thing.",
    "Let me tell you about the version of {TOPIC} nobody puts in the textbooks.",
    "Some ideas arrive like weather — you don't see them coming until you're already inside them.",
    "The extraordinary things hide behind the ordinary ones.",
    "There's more here than the surface allows.",
    "Pay attention — this matters more than it looks like it does.",
    "Beauty and difficulty almost always travel together.",
    "The quiet details carry the whole weight of the thing.",
  ],
  blog: [
    "Here's the {TOPIC} truth that took me far too long to learn.",
    "I've been sitting with this idea for a while now, and it's time to write it out.",
    "If you only take one thing from this piece, let it be this.",
    "This isn't another generic post about {TOPIC}. I promise.",
    "The first thing you need to know is the thing most people skip.",
    "Let me start with a question worth sitting with.",
    "Everything I thought I knew about {TOPIC} turned out to be... close, but not quite.",
    "Here's what actually changed my results — not what I expected.",
    "I've written about a lot of things. This one matters in a different way.",
    "The boring-looking insight is usually the most powerful one.",
    "Before we get practical, let's get clear on what we're actually solving.",
    "There's a right order to understanding {TOPIC}. Most people start at step three.",
    "The best way I can explain {TOPIC} is to start with what it isn't.",
    "I'm going to share something that shifted how I approach this entirely.",
    "Most content on {TOPIC} starts in the wrong place. Let's fix that.",
  ],
  email: [
    "I'm going to be direct with you today.",
    "Something you said (or someone like you said) has been on my mind.",
    "Quick question before we get into this — have you ever noticed that...",
    "I want to share something that I don't talk about often.",
    "You deserve a real answer to this, not a polished non-answer.",
    "This might be the most important thing I share with you this month.",
    "Let me get straight to the point, because your time matters.",
    "I've been testing this for the past few weeks and the results surprised me.",
    "This email is different from what I usually send. Read it slowly.",
    "There's a gap between what most people know about {TOPIC} and what works. Let's close it.",
    "If you've been feeling stuck with {TOPIC}, this is exactly why.",
    "I want to take you behind the curtain on {TOPIC} today.",
    "Three things. That's all this comes down to.",
    "Not a long email today. Just the one thing that matters most.",
    "This is the message I wish someone had sent me earlier.",
  ],
};

export const TRANSITIONS = {
  escalating: [
    "But here's where most frameworks fall short.",
    "Now — stay with me here, because this next part is where most people stop reading.",
    "That's only half of it though.",
    "Which brings us to the mechanism most people completely miss.",
    "Here's the part nobody explains clearly.",
    "And then something less obvious becomes clear.",
    "There's a deeper layer to this that's worth understanding.",
    "This is where the actual work begins.",
    "The next piece is what makes everything else make sense.",
    "Here's what changes when you understand this properly.",
  ],
  contrasting: [
    "But here's what most people get wrong.",
    "The problem? That's not actually what's happening.",
    "And yet — the evidence tells a different story.",
    "On the surface, that makes sense. Under the surface, it falls apart.",
    "That's the conventional view. Here's the inconvenient truth.",
    "Most people stop there. The ones who succeed don't.",
    "There's a catch, of course.",
    "It sounds right. It isn't.",
    "That would be great, if it were actually true.",
    "Easy to believe. Hard to defend when you look at the data.",
  ],
  exemplifying: [
    "Let me make this concrete.",
    "Here's what this actually looks like in practice.",
    "A real example makes this clearer.",
    "Consider what happens when you apply this directly.",
    "Think of it this way.",
    "Here's a scenario that captures exactly what I mean.",
    "Picture this for a moment.",
    "Let me break this down with something specific.",
    "The best way to see this is through an example.",
    "Take someone who's been dealing with exactly this.",
  ],
  emotional: [
    "And I think, at its core, this is really about something deeper.",
    "Here's the part that hits different when you really sit with it.",
    "This is where the emotional weight of {TOPIC} becomes impossible to ignore.",
    "Underneath all of this is a very human question.",
    "This is the part I always come back to.",
    "Forget the strategy for a second. This is what actually matters.",
    "There's something quietly profound in here, if you let it land.",
    "The reason this resonates so deeply is because...",
    "And when you get to the root of it, it's always about one thing.",
    "This is where honesty matters more than cleverness.",
  ],
  concluding: [
    "So where does that leave us?",
    "Here's what all of this actually means.",
    "Pull it all together and one thing becomes clear.",
    "At the end of all this thinking, one truth remains.",
    "This is what I keep coming back to.",
    "What does it all add up to?",
    "Strip away everything else and you're left with this.",
    "After everything — the research, the mistakes, the experiments — here's the conclusion.",
    "The bottom line, if there is one.",
    "And if I had to distill all of this into a single idea...",
  ],
};

export const EMOTIONAL_WORDS = {
  powerful: ["relentless", "unyielding", "electric", "unshakeable", "fierce", "raw", "unstoppable", "visceral", "consuming", "blazing"],
  tender: ["quiet", "gentle", "aching", "delicate", "tender", "soft", "fragile", "wistful", "lingering", "barely-there"],
  surprising: ["unexpected", "counterintuitive", "startling", "revealing", "hidden", "overlooked", "buried", "invisible", "forgotten", "misunderstood"],
  certain: ["undeniable", "irrefutable", "crystal-clear", "absolute", "definitive", "concrete", "proven", "verifiable", "unambiguous", "solid"],
  urgent: ["immediately", "right now", "before it's too late", "without delay", "urgently", "as soon as possible", "today", "this moment", "quickly", "without waiting"],
  hopeful: ["possible", "achievable", "within reach", "accessible", "real", "attainable", "closer than you think", "already in motion", "already yours", "almost there"],
  honest: ["truthfully", "frankly", "honestly", "to be direct", "without sugarcoating", "real talk", "let's be clear", "fair warning", "I'll be honest", "straight up"],
  wise: ["deeply", "fundamentally", "at its core", "essentially", "ultimately", "in truth", "when you really look at it", "beneath the surface", "at the root", "when it matters most"],
};

export const POWER_PHRASES = [
  "Most people never examine this closely enough.",
  "And that's where the real work lives.",
  "This is the one thing worth knowing.",
  "Everything else is downstream of this.",
  "Pay close attention to this.",
  "The answer was never complicated — just not obvious.",
  "Not many people will tell you this directly.",
  "This is what the evidence consistently shows.",
  "It's not about more. It's about better targeting.",
  "Precision beats intensity every time.",
  "The best version of this is simpler than it looks.",
  "This is the leverage point most people walk right past.",
  "Done consistently, this compounds in ways that are hard to overstate.",
  "One clear decision, made seriously, changes the trajectory.",
  "This is where most approaches stall. It doesn't have to.",
  "The gap between knowing and doing is the whole game.",
  "You don't need more information. You need more precision.",
  "Simple doesn't mean easy. There's an important difference.",
  "The ones who succeed aren't smarter — they're more specific.",
  "Stop optimizing what shouldn't be done at all.",
  "The obstacle you keep circling is usually the one worth addressing.",
  "Clarity here is worth more than any tactic.",
];

export const HUMAN_MARKERS = [
  "And look —",
  "Here's the thing:",
  "Honestly?",
  "Real talk:",
  "To be fair,",
  "And I say this knowing it'll land differently for different people:",
  "I could be wrong about this, but:",
  "For what it's worth,",
  "This took me embarrassingly long to figure out:",
  "I want to be clear about something:",
  "Here's what I've noticed:",
  "And this is the part I keep coming back to:",
  "Worth saying explicitly:",
  "Not to be dramatic, but:",
  "Let me be direct:",
  "Genuinely —",
  "This is the part nobody talks about:",
  "And I think that matters more than we admit:",
  "To put it plainly:",
  "In my experience —",
];

export const SENTENCE_STARTERS = [
  "The truth is,",
  "What most people don't realize is",
  "Here's the thing about",
  "One of the most",
  "When you really look at it,",
  "The reason",
  "What separates",
  "The single most important",
  "If there's one thing",
  "The question worth asking is",
  "The pattern I keep seeing is",
  "What actually happens when",
  "The difference between",
  "At its core,",
  "The most underrated",
  "Something worth noting:",
  "What nobody tells you is",
  "The biggest misconception about",
  "The real reason",
  "More than anything else,",
];

export const RHETORICAL_QUESTIONS = [
  "But what does that actually mean in practice?",
  "Why does this matter? Because the alternative is worse.",
  "Have you ever noticed how the simplest things are always the hardest to see?",
  "What would happen if you took this seriously — really seriously?",
  "Isn't that worth at least thinking about?",
  "How many times have you heard advice that sounded right but felt hollow?",
  "What if the thing you've been avoiding is the thing?",
  "When did we decide this was too hard to talk about honestly?",
  "What does it actually cost to stay where you are?",
  "Have you ever gotten to the end of something and wondered if you'd been asking the wrong question the whole time?",
  "Why is it that the people who know the most about a subject often say the least about it?",
  "What would change if you treated this as seriously as you treat everything else?",
  "Isn't this the question we should have started with?",
  "What would the version of you who'd already figured this out do differently today?",
  "Why do we make this harder than it has to be?",
];

export const SPECIFICITY_INJECTORS = [
  "not in theory — in actual practice",
  "not in the abstract, but specifically",
  "and I mean concretely, not conceptually",
  "with measurable, tangible results",
  "in real situations, with real stakes",
  "not once, but consistently",
  "not just for some people — for most people",
  "not as a philosophy, but as a daily practice",
  "backed by patterns we see again and again",
  "not the exception — the rule",
];

export const VIRAL_TRIGGERS = [
  "share this with someone who needs to hear it",
  "this is the part you screenshot",
  "bookmark this — you'll want to come back to it",
  "this will make sense at a specific moment in your life",
  "read this twice",
  "if this resonated, you already know what to do next",
  "the people who need this most are the ones who'll dismiss it first",
  "tag someone who's been thinking about this",
  "this is the part most people skip, and that's exactly why most people stay stuck",
  "the comment section on this is going to be interesting",
];

export const CLOSINGS: Record<string, string[]> = {
  inspiring: [
    "The version of this that actually works isn't complicated. It's just consistent. Start there.",
    "You don't need more information. You need one decision, made clearly, and then the discipline to follow through.",
    "Everything you're looking for is already available to you. The question is whether you're willing to go after it.",
    "The work is real. The results are real. The only variable is you.",
    "Start before you're ready. Stay longer than you're comfortable. That's the whole strategy.",
  ],
  reflective: [
    "Sometimes the most useful thing you can do is sit with a question rather than rush to an answer.",
    "The honest truth is that this takes time. And that's not a problem — that's the design.",
    "After everything, this is what I keep coming back to: the fundamentals, done well, are enough.",
    "I don't have all the answers here. But I've stopped pretending the question doesn't matter.",
    "The most valuable thing I've learned about {TOPIC} is how much I still have to learn.",
  ],
  actionable: [
    "Pick one thing from this. Apply it today. See what happens.",
    "Don't leave this with more information. Leave with one decision.",
    "The next step is simpler than you think: start.",
    "You've got everything you need. The only remaining question is what you do with it.",
    "Small movement today beats perfect planning forever. Move.",
  ],
  provocative: [
    "The people who read this and do nothing will be back here in a year with the same problem. You're not those people.",
    "This is the part where most content tells you 'good luck.' I'll tell you something better: you don't need luck.",
    "Here's the uncomfortable question to end on: what are you actually waiting for?",
    "Disagree with this? Good. Think harder. Then try it. Then tell me I was wrong.",
    "The gap between reading this and acting on it is the same gap that's always been there. Only one of you closes it.",
  ],
  youtube: [
    "If this hit different for you — drop a comment. I read all of them. And if you want more content like this, you already know what to do.",
    "That's everything. Now go actually use it — not tomorrow, not when you feel ready. Now.",
    "One more thing before you close this: share it with someone who needs to hear it today. You know exactly who that is.",
    "Subscribe if you're serious about this. Skip it if you're not. I'll be here either way.",
    "I'll see you in the next one. And if this helped — even a little — that's why I keep making these.",
  ],
};

export const PDF_CALLOUT_PHRASES = [
  "Key Insight:",
  "Worth Remembering:",
  "Critical Point:",
  "The Core Idea:",
  "Action Step:",
  "Important Note:",
  "The Bottom Line:",
  "Keep in Mind:",
  "Fundamental Truth:",
  "Remember This:",
];

export const PARAGRAPH_BRIDGES = [
  "Let's take this further.",
  "Now apply this to {TOPIC}.",
  "The next layer is this:",
  "Building on that —",
  "Which connects directly to something else:",
  "And this is where it gets more nuanced.",
  "Here's the practical application of everything above.",
  "Before we go further, let's make sure this is clear.",
  "Now for the part that makes the difference.",
  "With that foundation in place —",
];

export const TOPIC_AMPLIFIERS: Record<string, string[]> = {
  health: ["your energy", "your longevity", "your daily performance", "your mental clarity", "your body's signals", "your baseline", "what your body is actually asking for"],
  finance: ["your financial freedom", "your wealth-building timeline", "your money relationship", "your financial identity", "your earning ceiling", "your investment behavior", "what compound interest actually means for you"],
  mindset: ["your belief system", "your internal narrative", "your default assumptions", "your growth ceiling", "your self-image", "your unconscious patterns", "the story you're telling yourself"],
  relationships: ["your attachment patterns", "your communication defaults", "your conflict style", "your emotional availability", "your boundaries", "your love language", "what you actually need from others"],
  career: ["your professional trajectory", "your personal brand", "your value proposition", "your growth edge", "your leadership style", "your industry positioning", "how you're seen by the people who matter"],
  creativity: ["your creative process", "your original voice", "your idea generation habits", "your creative constraints", "your expression style", "your artistic identity", "where your best work comes from"],
  productivity: ["your focused hours", "your energy management", "your decision-making quality", "your deep work practice", "your distraction patterns", "your output-to-effort ratio", "what's actually on your plate"],
  business: ["your market positioning", "your customer psychology", "your revenue architecture", "your brand equity", "your scaling strategy", "your competitive moat", "what your business is actually built on"],
  education: ["your learning velocity", "your knowledge retention", "your understanding depth", "your skill acquisition method", "your mental models", "how you process new information", "what you actually remember"],
  technology: ["your digital workflow", "your automation leverage", "your tech stack", "your productivity multipliers", "your digital literacy", "your tool selection", "how technology is working for or against you"],
};
