// ── Human Voice & Emotional Authenticity Layer ────────────────────────────────
// The patterns that make content feel written by a person who has opinions,
// emotions, and a history — not generated by a process.
//
// Each pattern is calibrated to a specific emotional register:
// - Vulnerability: earning trust by showing fallibility
// - Conviction: communicating certainty without arrogance
// - Frustration: expressing genuine irritation at systemic problems
// - Humor: self-deprecating, wry, never forced
// - Empathy: recognizing why people make the mistakes they make
// - Skepticism: healthy pushback that eventually resolves
// - Enthusiasm: real interest, not performance
// - Self-correction: mid-thought refinement that reads as intelligent
// - Self-interruption: creating urgency and forward pull
// - Asides: parenthetical depth that rewards close reading

export const VOICE = {
  vulnerability: [
    "I'll be honest with you — I got this wrong for longer than I want to admit.",
    "Can I say something that might seem out of place here? I'm not sure I have this fully figured out either. But here's what I do know:",
    "I spent a long time believing the conventional version of this. The cost of that belief was real.",
    "Here's where I have to be careful not to oversimplify — because I overcomplicated this for years before I simplified it.",
    "I'm going to be direct, which means I'll also have to be honest about what I don't know.",
    "This is the part I almost didn't include, because it's less comfortable than the cleaner version.",
    "I had a version of this wrong for years. Not slightly off — structurally wrong.",
    "What I'm about to say is the thing I wish someone had told me earlier. Not because it would have been easy to hear, but because it would have been true.",
  ],

  conviction: [
    "I'm as confident about this as I am about anything I've worked on.",
    "After seeing this pattern repeat enough times, I've stopped hedging on it.",
    "This isn't a maybe. The evidence on this particular point is consistent enough that I'd stake my credibility on it.",
    "You can argue the nuances — and there are nuances — but the core of this is solid.",
    "I don't say this to sound authoritative. I say it because I've tested it enough to stop second-guessing it.",
    "Here's something I'm genuinely certain about, in a space full of things I'm not certain about:",
    "The one thing I'd tell someone with five minutes was this.",
    "This is where I stop using 'might' and 'often' and say plainly: this is how it works.",
  ],

  frustration: [
    "And honestly? This frustrates me. Because this is a knowable thing, and most advice on it is just wrong.",
    "Here's what I find genuinely irritating about the standard framing: it's optimized for simplicity, not accuracy.",
    "The thing that gets me is how preventable most of this is. The information exists. The problem is attention.",
    "I have a complicated relationship with the conventional wisdom here — mostly because I've watched it fail too many times.",
    "This is the part that bothers me the most. Not because it's hard — because it's being made unnecessarily hard.",
    "I want to be honest about something: most advice on this isn't bad because people are uninformed. It's bad because the incentives don't align with telling you the truth.",
    "What frustrates me isn't the problem — it's that the solution exists and isn't being talked about clearly.",
  ],

  humor: [
    "(Which, in hindsight, is both obvious and embarrassing.)",
    "(I paid good money to learn what I could have figured out for free. You're welcome.)",
    "(The irony was not lost on me — it just arrived late.)",
    "(This is me, gently, laughing at my past self.)",
    "(I'll spare you the full story, but let's say the lesson was expensive.)",
    "(Turns out 'just work harder' is not the framework I needed. Who knew.)",
    "(File this under 'things I wish I had known ten years ago and also yesterday.')",
    "(Spoiler: the conventional approach wasn't the problem. I was.)",
  ],

  empathy: [
    "And look — I understand why that approach is appealing. It makes complete sense. It just doesn't work.",
    "I'm not judging anyone for this. I did exactly the same thing, with equally earnest intentions.",
    "The reason most people get this wrong isn't a failure of intelligence — it's that the wrong approach looks completely right from the outside.",
    "There's a reason this mistake is so common: because the logic behind it is actually pretty sound. It's just missing one crucial piece.",
    "I want to be fair here — this is genuinely confusing territory. The conventional wisdom isn't crazy. It's just incomplete.",
    "If you've tried the standard approach and it didn't work, I want to say: that's not a personal failing. The approach itself has a design flaw.",
    "Most people make this mistake not because they don't care, but because caring doesn't tell you which direction to point it.",
  ],

  skepticism: [
    "I was genuinely skeptical when I first encountered this — which I think is the right reaction.",
    "My first response to this was to push back. That impulse turned out to be wrong, but I understand it.",
    "This sounds too clean — I know. My first reaction was the same.",
    "I'll give you my honest initial reaction: I didn't believe it either. Then I looked at the evidence.",
    "The skeptical response to this is reasonable. I had it. Here's what changed my mind.",
    "If this sounds too simple to be true, I understand the reaction. Simple things that work are also the most suspicious.",
    "I want to name the obvious objection before moving forward, because it's worth taking seriously:",
  ],

  enthusiasm: [
    "And this is where it gets genuinely interesting — not in a 'let me oversell this' way, but in a 'this is mechanically fascinating' way.",
    "I find this part legitimately exciting. Not performed excitement — actual 'this changes how I think about things' excitement.",
    "This is the piece I keep coming back to, because the implications keep expanding the more you sit with it.",
    "Okay — this is the part I was waiting to get to.",
    "Here's where it gets good. And I mean good in a specific, practical way.",
    "I love this particular insight. Not because it's clever, but because it's immediately useful.",
    "This is one of those ideas that, once you have it, you start seeing it everywhere.",
  ],

  selfCorrection: [
    "Well — not exactly. Let me be more precise about that, because the nuance matters.",
    "Actually, I want to revise that slightly — because the way I just put it isn't quite right.",
    "That's not quite the right framing. What I mean is something closer to this:",
    "Hold on — I phrased that too simply. The more accurate version:",
    "I said that in a way that makes it sound easier than it is. Let me be more honest:",
    "Let me correct something I implied there, because the implication could send you in the wrong direction:",
  ],

  selfInterruption: [
    "Wait — before I go further, there's something I need to add.",
    "Actually. Hold on. This is important enough to break the thread for.",
    "Let me stop here for a second, because this is easy to read past and hard to recover from if you do.",
    "I want to interrupt the flow because the thing I'm about to say is the thing this whole section is building toward.",
    "Stop. Read this next part carefully.",
    "One thing before I continue — and I mean this:",
  ],

  asides: [
    "(This one is worth sitting with for a moment before moving on.)",
    "(Write this down if you're tracking anything from this.)",
    "(This is the part most people skim. I'd encourage you not to.)",
    "(And yes — this applies to me too. Still does.)",
    "(Not a metaphor. Literally this.)",
    "(This is where most frameworks quietly fail, even the good ones.)",
    "(If nothing else from this lands, I hope this part does.)",
    "(I'm being specific on purpose here — generalities are easy to agree with and hard to act on.)",
  ],
};

// ── Voice Selection by Section Role ───────────────────────────────────────────
// Different section types call for different emotional registers.
// Problem sections earn trust through vulnerability + empathy.
// Insight sections use enthusiasm and skepticism → conviction arc.
// Contrarian sections use conviction + frustration (at the conventional approach).
// Action sections use empathy + asides (practical, grounded).
// Depth sections use self-correction + vulnerability (honest complexity).

export type VoiceType = keyof typeof VOICE;

export function pickVoice(category: VoiceType, index: number): string {
  const pool = VOICE[category];
  return pool[Math.abs(index) % pool.length] ?? "";
}

export function pickVoiceBlend(primary: VoiceType, secondary: VoiceType, index: number): string {
  // Returns primary for even indices, secondary for odd — creating natural variation
  return index % 2 === 0 ? pickVoice(primary, index) : pickVoice(secondary, index);
}
